# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AEX Engineering
title_short: AEX Eng
author: Massimiliano Zonta
email: info@aexengineering.com
phone: +39 04241931538
mobile: +39 3488590927
skype: massimiliano.zonta
address:
  Via tre ponti, 62
  <br>
  36061 Bassano del Grappa (VI)
  <br>
  Italy
description:  # this means to ignore newlines until "baseurl:"
 Automating user EXperience
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aexengineering.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  aexengineering
linkedin_username: aexengineering-di-ing-zonta-massimiliano

# Build settings
markdown: kramdown

# Other settings
sass:
 style: :compressed

# page size
page-width: 1280px
page-min-height: 900px
page_title_height: 120px
post_title_height: 200px
